### ISSUE TITLE
Does something really weird in 2021.2

### ISSUE THREAD

**Issue by Fangh** [upscalebaby/generic-serializable-dictionary#18]
![2022-01-29 15_42_19-Window](https://user-images.githubusercontent.com/6020679/151665257-e8ee9789-c704-463d-ac20-72765580fa98.png)

**Comment by upscalebaby** [comment]
Hey, yeah this hasn't been updated in a while and the reorderable arrays release was pretty messed up imo.

But good news is you can just uncomment the class attribute in the property drawer to disable it, or remove it and let Unity draw the data structure in the inspector.

I'll try to allocate some time to update this repo soon now that I think things have stabilized.

**Comment by upscalebaby** [comment]
Hey sorry for taking so long to get back to you.

I just made a new release with improvements to the property drawer and verified it now works in both 2021.1 and 2021.2.

https://github.com/upscalebaby/generic-serializable-dictionary/releases/tag/1.0.1

Thanks for your support in helping improve this project!
