### ISSUE TITLE
Inherit from ScriptableObject

### ISSUE THREAD

**Issue by marcospgp** [upscalebaby/generic-serializable-dictionary#19]
Shouldn't the dictionary inherit from ScriptableObject to avoid multiple references to the same dictionary becoming independent dictionaries upon deserialization?

**Comment by upscalebaby** [comment]
Hey, that sounds good. Also serializeReference could work I'm guessing.

I'll have a look when I get the chance thanks!

**Comment by marcospgp** [comment]
Nevermind, trying to instantiate a generic ScriptableObject-derived class returns null, with no exception being thrown. Sneaky!
