### ISSUE TITLE
First item overlaps when using nested collections

### ISSUE THREAD

**Issue by pajama** [upscalebaby/generic-serializable-dictionary#22]
Key is string, Value is a List<enum> 
All items except for the first expand well

![image](https://user-images.githubusercontent.com/2224105/171930504-9376dbfa-1000-4892-bc8f-9a25c4f97033.png)

**Comment by upscalebaby** [comment]
Hey! I'm almost certain it's related to this issue: https://issuetracker.unity3d.com/issues/first-array-element-expansion-is-broken-for-arrays-that-use-custom-property-drawers

**Comment by pajama** [comment]
Ah darn, that must be it. I'm using 2021.3.3. Nice find!
