### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by DataGreed** [upscalebaby/generic-serializable-dictionary#24]
I've placed GenericDictionaryPropertyDrawer in Assets/Editor and GenericDictionary in mys Assets folder, everything compiles, not errors, but my dictionaries are not rendered in inspector.

Do I miss something?

My dictionary declation goes like this:

`public Dictionary<DropPodType, GameObject> PodTypes=new Dictionary<DropPodType, GameObject>();`

`DropPodType` is a Enum.

**Comment by upscalebaby** [comment]
Hey! If you check the class name of the source file it's actually GenericDictionary.

I have it on my to-do be list to add a namespace and just call it Dictionary or SerializableDictionary but haven't had much time as of yet.

https://github.com/upscalebaby/generic-serializable-dictionary/blob/master/code_example1.PNG
