### ISSUE TITLE
Bug: Cant change dictonary entries

### ISSUE THREAD

**Issue by dano2595** [upscalebaby/generic-serializable-dictionary#3]
Hello,

thank you for your work! This feature was really missing in Unity.

Unfortunately I encountered a Bug with your Dictonary implementation. If I try to modify values in the Dictonary using the key and providing a new value. The new Value will be appended to the List and the Dictonary breaks.
```
GenericDictionary<string, int> myGenericDict;
myGenericDict.Add("test", 1);

// This will break the Dictionary
myGenericDict["test"] = 2;
```

I can get it to work if I rewrite the setter like this:
```
public TValue this[TKey key] {
    get => dictionary[key];
    set {
        //dictionary[key] = value;
        Remove(key);
        Add(key, value);
    }
}
```

Do you have another idea how to fix this issue? Removing and Adding a value just to change it seems unperformant for me.
Thank you for your help!

**Comment by upscalebaby** [comment]
Thanks for your report! I've verified the problem and will fix it today or over the weekend.

I've been meaning to add some tests and this issue is really motivating me to look into that after this. Thank you for your time.

**Comment by upscalebaby** [comment]
Update: I haven't dog fooded this project enough yet, been busy with some work stuff past couple months. I'm very glad you pointed this out and I've been trying this out some more as well. Currently I'm working on a solution that will fix this issue and also add some nice improvements overall if all goes well.

**Comment by upscalebaby** [comment]
The latest commit contains the fix for this issue, feel free to open another issue if you experience any problems and thanks again for your time!
