### ISSUE TITLE
Inspector can't distinguish between multiple dictionaries

### ISSUE THREAD

**Issue by NoCultist** [upscalebaby/generic-serializable-dictionary#5]
I'm sorry to bring more bad news but I just stumbled upon this weird occurrence:

![output](https://user-images.githubusercontent.com/19191981/98818629-1dad7500-242c-11eb-9f6e-65bc81cbbfd3.gif)

My guess is that it's caused by the line:
`var list = property.FindPropertyRelative("list");`
in GenericDictionaryPropertyDrawer.cs but I'm no expert (if I were I'd provide you with solution not an issue 😅)

I hope it won't be too hard to resolve because this is something I need from Unity surprisingly often...

And once again
Stay safe and have a nice day

**Comment by upscalebaby** [comment]
Haha it's fine, I want to improve the project and your findings are helping a lot.

Just to make sure we're on the same page, what is the data structure that generated this issue? Is it a list of GenericDictionaries perhaps?

**Comment by upscalebaby** [comment]
A small update for you: I haven't had as much time as I'd like to work on this - but it's a very interesting find, and an important one to fix.

I've found what's causing this issue, and I just need to rewrite a portion of the PropertyDrawer to fix it.

The issue occurs in the do-while-loop inside the PropertyDrawer. For some reason I don't understand Unity skips to the next array entry when calling serializedProperty.NextVisible(true) when the property is inside a list.

Good news is that this does not happend when using an Enumerator for the serializedProperty, so this will be fixed within the coming days.

Thanks again for your support and patience.
